export const APP = {
  header: "app-header",
  logo: "sfr-logo",
  navDashboard: "nav-dashboard",
  navInvoices: "nav-invoices",
  userMenu: "user-menu-button",
  footer: "app-footer",
};

export const INVOICES = {
  list: "invoices-list",
  card: "invoice-card",
  status: "invoice-status-badge",
  payButton: "invoice-pay-button",
  receiptButton: "invoice-receipt-button",
  unpaidCount: "unpaid-count",
  totalDue: "total-due-amount",
  emptyState: "invoices-empty-state",
};

export const DETAIL = {
  screen: "invoice-detail-screen",
  amount: "detail-amount",
  failureCard: "failure-info-card",
  failureReason: "failure-reason",
  failureCode: "failure-code",
  failureDate: "failure-date",
  attempts: "failure-attempts",
  mandateStatus: "mandate-status-badge",
  ibanMasked: "detail-iban-masked",
  txnRef: "detail-transaction-ref",
  copyRef: "copy-transaction-ref",
  history: "attempt-history-toggle",
  regulariserCard: "regulariser-card",
  cardOption: "payment-method-card-option",
  retryPayment: "retry-payment-button",
  downloadInvoice: "download-invoice-button",
  help1023: "help-1023-button",
  nextAttempt: "next-attempt-info",
  back: "detail-back-button",
};

export const PAYMENT = {
  screen: "payment-screen",
  summaryAmount: "payment-summary-amount",
  cardNumber: "cc-number-input",
  cardHolder: "cc-holder-input",
  expiry: "cc-expiry-input",
  cvv: "cc-cvv-input",
  submit: "payment-submit-button",
  cancel: "payment-cancel-button",
  errorField: "payment-field-error",
  processing: "payment-processing-screen",
  success: "payment-success-screen",
  successReference: "payment-success-reference",
  downloadReceipt: "download-receipt-button",
  backToInvoices: "back-to-invoices-button",
  failure: "payment-failure-screen",
  failureMessage: "payment-failure-message",
  retry: "payment-retry-button",
};
