export const AUTH = {
  loginIdentifier: "login-identifier-input",
  loginPassword: "login-password-input",
  loginRemember: "login-remember-checkbox",
  loginSubmit: "login-submit-button",
  loginError: "login-error-message",
  forgotPasswordLink: "forgot-password-link",
  forgotIdentifierLink: "forgot-identifier-link",
  forgotPasswordEmail: "forgot-password-email-input",
  forgotPasswordSubmit: "forgot-password-submit-button",
  forgotPasswordSuccess: "forgot-password-success-message",
  forgotIdentifierEmail: "forgot-identifier-email-input",
  forgotIdentifierSubmit: "forgot-identifier-submit-button",
  forgotIdentifierSuccess: "forgot-identifier-success-message",
  resetPassword: "reset-password-input",
  resetPasswordConfirm: "reset-password-confirm-input",
  resetPasswordSubmit: "reset-password-submit-button",
  resetPasswordError: "reset-password-error-message",
  resetPasswordSuccess: "reset-password-success-message",
  logoutButton: "logout-button",
  backToLoginLink: "back-to-login-link",
};
